### ISSUE TITLE
HMR does not reload when using Docker

### ISSUE THREAD

**Issue by JoseCMRocha** [pmmmwh/react-refresh-webpack-plugin#348]
It seems that using Docker as development environment does not refresh the page on changes.

Using the example webpack-hot-middleware I am able to start node and when changing a file the browser refresh with the latest changes.

However if I use docker as a mean to have an dockerized development environment on starting the app I see on the browser "[HMR] connected" but on changing a file refresh does not happens.

To reproduce this just use the example for webpack-hot-middleware and create a DockerFile and a docker-compose.yml

```
# DOCKERFILE
FROM node:14

RUN mkdir -p /workspaces/app
WORKDIR /workspaces/app

COPY package.json ./
RUN npm install

CMD [ "npm", "run", "start" ]
```
```
# DOCKERCOMPOSE
version: "3.9"

services:
  frontend:
    container_name: frontend
    ports:
      - '5002:3000'
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/workspaces/app:rw
      - /workspaces/app/node_modules
```

I trying to work around with configurations without success what led me to believe this could be a limitation of this plugin.

Thanks for the time, spend reading this issue.
